module.exports = {
    Ruby: 'Ruby',
    JavaScript: 'js',
    Rust: 'rustlang',
    Kotlin: 'kotlin',
    Dart: 'dart',
    Python: 'python',
    CSharp: 'csharp',
    GoLang: 'golang',
    CPlusPlus: 'cpp',
    Java: 'java',
    TypeScript: 'typescript',
    Swift: 'swift',
    ObjectiveC: 'objc',
    Elm: 'elm',
    Pike: 'pike',
    Haskell: 'haskell',
    Crystal: 'crystal',
  };